jwt:
  header: Authorization
  prefix: Bearer
  secret: ${secret:frhaeaawegawgrw}
  accessExpiration: 3600
  refreshExpiration: 604800

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/dayt?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '0504'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

redis:
  host: localhost
  port: 6379